# SonarCloud Configuration
# https://docs.sonarsource.com/sonarcloud/advanced-setup/analysis-parameters/

# Rule exclusions
# typescript:S3735 - "void" operator usage
# Event files REQUIRE `void DOMAIN_ID` to satisfy ESLint rule `no-missing-domain-id`
# which mandates a local DOMAIN_ID constant in every domain event file.
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S3735
sonar.issue.ignore.multicriteria.e1.resourceKey=src/**/events/*Events.ts
