/**
 * git API Mock Data
 * GitHub-like mock data for development and testing
 */

import type {
  GitRepository,
  GitTreeEntry,
  GitBranch,
  GitFileContent,
  GitComment,
  GitOwner,
} from '../types/gitTypes';

const mockOwner: GitOwner = {
  login: 'octocat',
  id: 1,
  avatar_url: 'https://avatars.githubusercontent.com/u/583231?v=4',
  html_url: 'https://github.com/octocat',
};

const mockCollaborator: GitOwner = {
  login: 'mona',
  id: 2,
  avatar_url: 'https://avatars.githubusercontent.com/u/9919?v=4',
  html_url: 'https://github.com/mona',
};

export const mockRepository: GitRepository = {
  id: 1296269,
  name: 'hello-world',
  full_name: 'octocat/hello-world',
  owner: mockOwner,
  description: 'My first repository on GitHub!',
  html_url: 'https://github.com/octocat/hello-world',
  language: 'TypeScript',
  default_branch: 'main',
  stargazers_count: 1842,
  forks_count: 523,
  open_issues_count: 47,
  created_at: '2024-01-15T09:00:00Z',
  updated_at: '2025-03-28T14:32:00Z',
  private: false,
  topics: ['typescript', 'react', 'frontend'],
};

export const mockTreeRoot: GitTreeEntry[] = [
  { path: 'src', name: 'src', type: 'dir', size: 0, sha: 'abc001' },
  { path: 'docs', name: 'docs', type: 'dir', size: 0, sha: 'abc002' },
  { path: '.github', name: '.github', type: 'dir', size: 0, sha: 'abc003' },
  { path: 'package.json', name: 'package.json', type: 'file', size: 1245, sha: 'abc004' },
  { path: 'tsconfig.json', name: 'tsconfig.json', type: 'file', size: 423, sha: 'abc005' },
  { path: 'README.md', name: 'README.md', type: 'file', size: 2048, sha: 'abc006' },
  { path: 'vite.config.ts', name: 'vite.config.ts', type: 'file', size: 890, sha: 'abc007' },
  { path: '.gitignore', name: '.gitignore', type: 'file', size: 310, sha: 'abc008' },
];

export const mockTreeSrc: GitTreeEntry[] = [
  { path: 'src/main.tsx', name: 'main.tsx', type: 'file', size: 1520, sha: 'def001' },
  { path: 'src/App.tsx', name: 'App.tsx', type: 'file', size: 3200, sha: 'def002' },
  { path: 'src/components', name: 'components', type: 'dir', size: 0, sha: 'def003' },
  { path: 'src/hooks', name: 'hooks', type: 'dir', size: 0, sha: 'def004' },
  { path: 'src/utils', name: 'utils', type: 'dir', size: 0, sha: 'def005' },
  { path: 'src/types.ts', name: 'types.ts', type: 'file', size: 890, sha: 'def006' },
];

export const mockBranches: GitBranch[] = [
  { name: 'main', sha: 'a1b2c3d4', protected: true },
  { name: 'develop', sha: 'e5f6g7h8', protected: false },
  { name: 'feature/monaco-editor', sha: 'i9j0k1l2', protected: false },
  { name: 'fix/comment-rendering', sha: 'm3n4o5p6', protected: false },
];

export const mockFiles: Record<string, GitFileContent> = {
  'src/main.tsx': {
    name: 'main.tsx',
    path: 'src/main.tsx',
    sha: 'def001',
    size: 520,
    content: [
      "import { StrictMode } from 'react';",
      "import { createRoot } from 'react-dom/client';",
      "import App from './App';",
      "import './index.css';",
      '',
      '/**',
      ' * Application entry point',
      ' * Initializes React with StrictMode',
      ' */',
      "createRoot(document.getElementById('root')!).render(",
      '  <StrictMode>',
      '    <App />',
      '  </StrictMode>',
      ');',
    ].join('\n'),
    encoding: 'utf-8',
    language: 'typescript',
    html_url: 'https://github.com/octocat/hello-world/blob/main/src/main.tsx',
  },
  'src/App.tsx': {
    name: 'App.tsx',
    path: 'src/App.tsx',
    sha: 'def002',
    size: 8400,
    content: [
      "import React, { useState, useCallback, useEffect, useMemo, useRef } from 'react';",
      "import { Header } from './components/Header';",
      "import { Sidebar } from './components/Sidebar';",
      "import { MainContent } from './components/MainContent';",
      "import { Footer } from './components/Footer';",
      "import { NotificationCenter } from './components/NotificationCenter';",
      "import { SearchOverlay } from './components/SearchOverlay';",
      "import { useTheme } from './hooks/useTheme';",
      "import { useKeyboardShortcuts } from './hooks/useKeyboardShortcuts';",
      "import { useLocalStorage } from './hooks/useLocalStorage';",
      "import { useMediaQuery } from './hooks/useMediaQuery';",
      "import type { AppConfig, UserPreferences, Notification } from './types';",
      "import { AppContext, type AppContextValue } from './context/AppContext';",
      "import { ErrorBoundary } from './components/ErrorBoundary';",
      "import { logger } from './utils/logger';",
      '',
      '// ──────────────────────────────────────────────',
      '// Constants',
      '// ──────────────────────────────────────────────',
      '',
      "const APP_VERSION = '2.1.0';",
      'const SIDEBAR_BREAKPOINT = 768;',
      'const MAX_NOTIFICATIONS = 50;',
      'const NOTIFICATION_DISMISS_DELAY = 5000;',
      '',
      '// ──────────────────────────────────────────────',
      '// Types',
      '// ──────────────────────────────────────────────',
      '',
      'interface AppState {',
      '  sidebarOpen: boolean;',
      '  searchOpen: boolean;',
      '  notificationsOpen: boolean;',
      '  activePanel: string | null;',
      '}',
      '',
      'type AppAction =',
      "  | { type: 'TOGGLE_SIDEBAR' }",
      "  | { type: 'TOGGLE_SEARCH' }",
      "  | { type: 'TOGGLE_NOTIFICATIONS' }",
      "  | { type: 'SET_ACTIVE_PANEL'; payload: string | null }",
      "  | { type: 'CLOSE_ALL_PANELS' };",
      '',
      '// ──────────────────────────────────────────────',
      '// Reducer',
      '// ──────────────────────────────────────────────',
      '',
      'function appReducer(state: AppState, action: AppAction): AppState {',
      '  switch (action.type) {',
      "    case 'TOGGLE_SIDEBAR':",
      '      return { ...state, sidebarOpen: !state.sidebarOpen };',
      '',
      "    case 'TOGGLE_SEARCH':",
      '      return {',
      '        ...state,',
      '        searchOpen: !state.searchOpen,',
      '        notificationsOpen: false,',
      '      };',
      '',
      "    case 'TOGGLE_NOTIFICATIONS':",
      '      return {',
      '        ...state,',
      '        notificationsOpen: !state.notificationsOpen,',
      '        searchOpen: false,',
      '      };',
      '',
      "    case 'SET_ACTIVE_PANEL':",
      '      return { ...state, activePanel: action.payload };',
      '',
      "    case 'CLOSE_ALL_PANELS':",
      '      return {',
      '        ...state,',
      '        searchOpen: false,',
      '        notificationsOpen: false,',
      '        activePanel: null,',
      '      };',
      '',
      '    default:',
      '      return state;',
      '  }',
      '}',
      '',
      'const initialAppState: AppState = {',
      '  sidebarOpen: true,',
      '  searchOpen: false,',
      '  notificationsOpen: false,',
      '  activePanel: null,',
      '};',
      '',
      '// ──────────────────────────────────────────────',
      '// Custom hooks',
      '// ──────────────────────────────────────────────',
      '',
      '/**',
      ' * Manages notification queue with auto-dismiss',
      ' */',
      'function useNotifications() {',
      '  const [notifications, setNotifications] = useState<Notification[]>([]);',
      '  const timersRef = useRef<Map<string, ReturnType<typeof setTimeout>>>(new Map());',
      '',
      '  const addNotification = useCallback((notification: Omit<Notification, "id" | "timestamp">) => {',
      '    const id = `notif-${Date.now()}-${Math.random().toString(36).slice(2)}`;',
      '    const newNotification: Notification = {',
      '      ...notification,',
      '      id,',
      '      timestamp: Date.now(),',
      '    };',
      '',
      '    setNotifications((prev) => {',
      '      const updated = [newNotification, ...prev];',
      '      return updated.slice(0, MAX_NOTIFICATIONS);',
      '    });',
      '',
      '    // Auto-dismiss non-error notifications',
      "    if (notification.type !== 'error') {",
      '      const timer = setTimeout(() => {',
      '        dismissNotification(id);',
      '      }, NOTIFICATION_DISMISS_DELAY);',
      '      timersRef.current.set(id, timer);',
      '    }',
      '',
      '    return id;',
      '  }, []);',
      '',
      '  const dismissNotification = useCallback((id: string) => {',
      '    setNotifications((prev) => prev.filter((n) => n.id !== id));',
      '    const timer = timersRef.current.get(id);',
      '    if (timer) {',
      '      clearTimeout(timer);',
      '      timersRef.current.delete(id);',
      '    }',
      '  }, []);',
      '',
      '  const clearAll = useCallback(() => {',
      '    timersRef.current.forEach((timer) => clearTimeout(timer));',
      '    timersRef.current.clear();',
      '    setNotifications([]);',
      '  }, []);',
      '',
      '  // Cleanup timers on unmount',
      '  useEffect(() => {',
      '    return () => {',
      '      timersRef.current.forEach((timer) => clearTimeout(timer));',
      '    };',
      '  }, []);',
      '',
      '  return { notifications, addNotification, dismissNotification, clearAll };',
      '}',
      '',
      '// ──────────────────────────────────────────────',
      '// Main App Component',
      '// ──────────────────────────────────────────────',
      '',
      '/**',
      ' * Root application component',
      ' *',
      ' * Manages global layout, theme, notifications,',
      ' * keyboard shortcuts, and responsive behaviour.',
      ' */',
      'const App: React.FC = () => {',
      '  const [state, dispatch] = React.useReducer(appReducer, initialAppState);',
      '  const { theme, toggleTheme, setTheme } = useTheme();',
      '  const [preferences, setPreferences] = useLocalStorage<UserPreferences>(',
      "    'app-preferences',",
      '    { compactMode: false, fontSize: 14, language: "en" }',
      '  );',
      '  const isMobile = useMediaQuery(`(max-width: ${SIDEBAR_BREAKPOINT}px)`);',
      '  const { notifications, addNotification, dismissNotification, clearAll } = useNotifications();',
      '',
      '  // Close sidebar on mobile by default',
      '  useEffect(() => {',
      '    if (isMobile && state.sidebarOpen) {',
      "      dispatch({ type: 'TOGGLE_SIDEBAR' });",
      '    }',
      '  }, [isMobile]); // eslint-disable-line react-hooks/exhaustive-deps',
      '',
      '  // Keyboard shortcuts',
      '  useKeyboardShortcuts({',
      "    'mod+b': () => dispatch({ type: 'TOGGLE_SIDEBAR' }),",
      "    'mod+k': () => dispatch({ type: 'TOGGLE_SEARCH' }),",
      "    'Escape': () => dispatch({ type: 'CLOSE_ALL_PANELS' }),",
      '  });',
      '',
      '  // Build app configuration',
      '  const config: AppConfig = useMemo(',
      '    () => ({',
      '      theme,',
      '      sidebarOpen: state.sidebarOpen,',
      '      version: APP_VERSION,',
      '      compactMode: preferences.compactMode,',
      '      fontSize: preferences.fontSize,',
      '    }),',
      '    [theme, state.sidebarOpen, preferences.compactMode, preferences.fontSize]',
      '  );',
      '',
      '  // Context value for deeply nested components',
      '  const contextValue: AppContextValue = useMemo(',
      '    () => ({',
      '      config,',
      '      preferences,',
      '      setPreferences,',
      '      addNotification,',
      '      theme,',
      '      toggleTheme,',
      '    }),',
      '    [config, preferences, setPreferences, addNotification, theme, toggleTheme]',
      '  );',
      '',
      '  const handleToggleSidebar = useCallback(() => {',
      "    dispatch({ type: 'TOGGLE_SIDEBAR' });",
      '  }, []);',
      '',
      '  const handleToggleSearch = useCallback(() => {',
      "    dispatch({ type: 'TOGGLE_SEARCH' });",
      '  }, []);',
      '',
      '  const handleToggleNotifications = useCallback(() => {',
      "    dispatch({ type: 'TOGGLE_NOTIFICATIONS' });",
      '  }, []);',
      '',
      '  const handleThemeChange = useCallback(',
      "    (newTheme: 'light' | 'dark' | 'system') => {",
      '      setTheme(newTheme);',
      "      logger.info('Theme changed', { theme: newTheme });",
      '      addNotification({',
      "        type: 'info',",
      '        title: "Theme updated",',
      '        message: `Switched to ${newTheme} mode`,',
      '      });',
      '    },',
      '    [setTheme, addNotification]',
      '  );',
      '',
      '  const handlePreferencesChange = useCallback(',
      '    (updates: Partial<UserPreferences>) => {',
      '      setPreferences((prev) => ({ ...prev, ...updates }));',
      "      logger.info('Preferences updated', updates);",
      '    },',
      '    [setPreferences]',
      '  );',
      '',
      '  // ── Render ──────────────────────────────────',
      '',
      '  return (',
      '    <ErrorBoundary',
      '      fallback={<div className="error-screen">Something went wrong</div>}',
      '      onError={(error) => {',
      "        logger.error('App ErrorBoundary caught', error);",
      '        addNotification({',
      "          type: 'error',",
      "          title: 'Unexpected error',",
      '          message: error.message,',
      '        });',
      '      }}',
      '    >',
      '      <AppContext.Provider value={contextValue}>',
      '        <div',
      '          className={`app ${theme} ${preferences.compactMode ? "compact" : ""}`}',
      '          style={{ fontSize: preferences.fontSize }}',
      '        >',
      '          <Header',
      '            config={config}',
      '            notificationCount={notifications.length}',
      '            onToggleSidebar={handleToggleSidebar}',
      '            onToggleSearch={handleToggleSearch}',
      '            onToggleNotifications={handleToggleNotifications}',
      '            onThemeChange={handleThemeChange}',
      '          />',
      '',
      '          <div className="app-body">',
      '            <Sidebar',
      '              open={state.sidebarOpen}',
      '              compact={isMobile}',
      '              activePanel={state.activePanel}',
      "              onPanelChange={(panel) => dispatch({ type: 'SET_ACTIVE_PANEL', payload: panel })}",
      '            />',
      '',
      '            <MainContent',
      '              config={config}',
      '              onPreferencesChange={handlePreferencesChange}',
      '            />',
      '          </div>',
      '',
      '          <Footer version={APP_VERSION} />',
      '',
      '          {/* Overlay panels */}',
      '          {state.searchOpen && (',
      '            <SearchOverlay',
      "              onClose={() => dispatch({ type: 'TOGGLE_SEARCH' })}",
      '              onResultSelect={(result) => {',
      "                logger.info('Search result selected', result);",
      "                dispatch({ type: 'CLOSE_ALL_PANELS' });",
      '              }}',
      '            />',
      '          )}',
      '',
      '          {state.notificationsOpen && (',
      '            <NotificationCenter',
      '              notifications={notifications}',
      '              onDismiss={dismissNotification}',
      '              onClearAll={clearAll}',
      "              onClose={() => dispatch({ type: 'TOGGLE_NOTIFICATIONS' })}",
      '            />',
      '          )}',
      '        </div>',
      '      </AppContext.Provider>',
      '    </ErrorBoundary>',
      '  );',
      '};',
      '',
      'export default App;',
    ].join('\n'),
    encoding: 'utf-8',
    language: 'typescript',
    html_url: 'https://github.com/octocat/hello-world/blob/main/src/App.tsx',
  },
  'README.md': {
    name: 'README.md',
    path: 'README.md',
    sha: 'abc006',
    size: 512,
    content: [
      '# Hello World',
      '',
      'A modern React application built with TypeScript and Vite.',
      '',
      '## Features',
      '',
      '- **Fast HMR** with Vite',
      '- **Type Safety** with TypeScript',
      '- **Component Library** with shadcn/ui',
      '- **State Management** with Redux Toolkit',
      '',
      '## Getting Started',
      '',
      '```bash',
      'npm install',
      'npm run dev',
      '```',
      '',
      '## License',
      '',
      'MIT',
    ].join('\n'),
    encoding: 'utf-8',
    language: 'markdown',
    html_url: 'https://github.com/octocat/hello-world/blob/main/README.md',
  },
  'package.json': {
    name: 'package.json',
    path: 'package.json',
    sha: 'abc004',
    size: 645,
    content: JSON.stringify({
      name: 'hello-world',
      version: '2.0.0',
      private: true,
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'tsc && vite build',
        preview: 'vite preview',
        lint: 'eslint . --ext ts,tsx',
      },
      dependencies: {
        react: '^19.0.0',
        'react-dom': '^19.0.0',
      },
      devDependencies: {
        '@types/react': '^19.0.0',
        typescript: '^5.7.0',
        vite: '^6.0.0',
      },
    }, null, 2),
    encoding: 'utf-8',
    language: 'json',
    html_url: 'https://github.com/octocat/hello-world/blob/main/package.json',
  },
};

export const mockComments: Record<string, GitComment[]> = {
  'src/App.tsx': [
    {
      id: 101,
      body: 'MAX_NOTIFICATIONS should be configurable via environment variable or app config instead of a hardcoded constant.',
      line: 23,
      lineEnd: 24,
      path: 'src/App.tsx',
      user: mockCollaborator,
      status: 'active',
      created_at: '2025-03-25T10:15:00Z',
      updated_at: '2025-03-25T10:15:00Z',
      replies: [
        {
          id: 201,
          body: 'Agreed — I\'ll move it to the AppConfig type and read from env.',
          user: mockOwner,
          created_at: '2025-03-25T11:30:00Z',
        },
      ],
    },
    {
      id: 102,
      body: 'The `useNotifications` hook is getting large. Consider extracting it to its own file under hooks/.',
      line: 97,
      lineEnd: 148,
      path: 'src/App.tsx',
      user: mockCollaborator,
      status: 'active',
      created_at: '2025-03-24T08:45:00Z',
      updated_at: '2025-03-25T09:00:00Z',
      replies: [],
    },
    {
      id: 103,
      body: 'The eslint-disable comment on line 175 suppresses an exhaustive-deps warning. Can we fix the dependency array instead?',
      line: 175,
      lineEnd: 175,
      path: 'src/App.tsx',
      user: mockCollaborator,
      status: 'active',
      created_at: '2025-03-26T14:20:00Z',
      updated_at: '2025-03-26T14:20:00Z',
      replies: [
        {
          id: 203,
          body: 'We intentionally run this effect only when isMobile changes, not when sidebarOpen changes. The disable is correct here.',
          user: mockOwner,
          created_at: '2025-03-26T15:00:00Z',
        },
      ],
    },
    {
      id: 107,
      body: 'Consider using `clsx` or `cn` utility for the className composition here — the ternary in the template literal is getting hard to read.',
      line: 258,
      lineEnd: 259,
      path: 'src/App.tsx',
      user: mockCollaborator,
      status: 'resolved',
      created_at: '2025-03-27T16:00:00Z',
      updated_at: '2025-03-28T10:00:00Z',
      replies: [],
    },
  ],
  'src/main.tsx': [
    {
      id: 104,
      body: 'Non-null assertion on getElementById is acceptable here since root element is in index.html.',
      line: 10,
      lineEnd: 10,
      path: 'src/main.tsx',
      user: mockOwner,
      status: 'active',
      created_at: '2025-03-20T16:00:00Z',
      updated_at: '2025-03-20T16:00:00Z',
      replies: [],
    },
  ],
  'README.md': [
    {
      id: 105,
      body: 'We should add a "Contributing" section with guidelines for PRs and code style.',
      line: 6,
      lineEnd: 6,
      path: 'README.md',
      user: mockCollaborator,
      status: 'active',
      created_at: '2025-03-27T09:00:00Z',
      updated_at: '2025-03-27T09:00:00Z',
      replies: [
        {
          id: 202,
          body: 'Agreed — I\'ll draft a CONTRIBUTING.md and link it from here.',
          user: mockOwner,
          created_at: '2025-03-27T11:00:00Z',
        },
      ],
    },
    {
      id: 106,
      body: 'The Getting Started steps should mention the minimum Node.js version required.',
      line: 14,
      lineEnd: 16,
      path: 'README.md',
      user: mockCollaborator,
      status: 'active',
      created_at: '2025-03-28T08:30:00Z',
      updated_at: '2025-03-28T08:30:00Z',
      replies: [],
    },
  ],
};
